language: java
addons:
  apt:
    packages:
    - xmlstarlet
    - graphviz
jdk:
- oraclejdk11
after_success:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- ./can_auto_deploy.sh && mvn deploy --settings settings.xml
env:
  global:
  - secure: T7PdKFcN1dMQQSyzBdFnKMtOFoMnytPv1JJCXJVIWbMZodsCUR1J4g6SJER/Hf2J79+Wbf4W/vt5kBxky/2QPpLZBjLbzgbxT6fXbl3PzQSJhskdLoVxnep3Oya8X6I3wqPibQrscaCCYGHv9N4RgS3o6pJ1o/ddtVb5bHzb9vHOb3jD5tinmnlk/dmXHm6U+R5i48JJlacH4Q2PUwGfHV4v4xDD4fvcG1UyCJah1NtrlNSXc3NQ713j5ctDtFYj9nOCNE8sI/zkjYSE9eD/o6yapubRlPRJlC8pD1uzjEiTzQeuzQ+SH4+BUlA4niSL8dnlEKkDfZjEf1MKe8T4gzAN6Y4FOxA/BoubdNqB3/EG/f5qOffxGI7aLli9Kqf0EpkW1Ymavk66qXh4kCZ4nRrga4jwrrxs0oeS5xY3+p+zfra+9SO+Y7oEP0+2lVY7g19KTWJtf01gVZ4zVcZCFeIsIW3Xj6HfJV67QObwsxuPCigR3LmY6P6GD0fmBWYHFQaTtUPYFREichyIgQL1e6j2VIlDW7eoRC8q8Klivj19b2zqMUKudaPMpBACUnhIUQYX8C5yH/Evoln7jkSp2WMJPucbZfAE3myqh66XZkVJXzSZSST7U/joEH5O7kasQGYj6p/AKpP5Bir++cHOdpclarZSL25PvfUiC5KGg7k=
  - secure: tccDWRTC80HpC56fEIl6mbup8Xt3xrsa0CYhRlm4gKBEDp1qtaZt5BDTDLZ82BOXJk7P5YNrC5UFFjl1W0CmCzGSC3LkNhiK9uYgPsqZLUpzeTK18YGIBm/Qn+esrZJNr+qUM/lFWcQEarRKaWQjpUUqFTcs0+zWZbVfY26lMMB4itWDQ/rJgGGmMfUjSyCFn1rY1tvyX+G4zatYFEKiGzs9gVP8qVifbXpvuPfIb2E/wx2MuFVIQIVVdXb4K36VOgFKFtTw8L6X2b0TBUylFnfJIzPKihoZkm3lmWJYL/vcf41vWpugDJ/o5QdqDIZJam/uyRoTLkdLttlKppdvl9D8PErx2XW0L5ds+weLTjwkDj44ySKLyswJfMUHnR0k7J4caIXisnpM8uicpCwZ6zLw4ar4xIT5afD0y8Dq+fTbbwXg+mM/M2H9FV397MRx+o7hcb9/vSC+XkGAm7RGM2So5ewksqistBbnP6Gzh0qPY1Vl3cOHCmwvtbkQYKpELDUkmUkupYtrYuLrCgnG13rz0MvVLvDodFncEOkPRMcYY4FSMVtCZybzLWwYIenRWvzfC4ZMqJJ5F4bJC7D1pmdYBr+dKMUH5ZTHJvffJcE5pt2/yFGrcEHrrzx+Kvw7bapoqZ7XjQ69YNv4XoylLavXfoINSwG4a56wAbCWBJE=
